### ISSUE TITLE
+jobs command parsing failure

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#44]
Repro Steps
1. NOTE: The helpfile for +jobs is currently empty, so I guessed at the syntax...
2. `+jobs/create REQ/Posebreak=It'd probably be good if posebreak was disabled in OOC spaces.`

Expected Outcome:
Job is created, no error

Actual Outcome:
I think the job is created, this is the output I get:
```
No queue specified or found. Created and assigned to 'Default'.
Job 'REQ/Posebreak' created with ID 1.
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "/root/game/commands/jobs/jobs_commands.py", line 82, in func
    self.create_job()
  File "/root/game/commands/jobs/jobs_commands.py", line 275, in create_job
    self.post_to_jobs_channel(self.caller.name, job.id, "created")
  File "/root/game/commands/jobs/jobs_commands.py", line 764, in post_to_jobs_channel
    channel = create.create_channel("Jobs", typeclass="evennia.comms.comms.Channel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/comms/managers.py", line 494, in create_channel
    typeclass = class_from_module(typeclass, settings.TYPECLASS_PATHS)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/utils/utils.py", line 1668, in class_from_module
    raise ImportError(err)
ImportError: 
Could not load typeclass 'evennia.comms.comms.Channel'
Paths searched:
    evennia.comms.comms.Channel
    typeclasses.evennia.comms.comms.Channel
    evennia.evennia.comms.comms.Channel
    evennia.contrib.evennia.comms.comms.Channel
    evennia.contrib.game_systems.evennia.comms.comms.Channel
    evennia.contrib.base_systems.evennia.comms.comms.Channel
    evennia.contrib.full_systems.evennia.comms.comms.Channel
    evennia.contrib.tutorials.evennia.comms.comms.Channel
    evennia.contrib.utils.evennia.comms.comms.Channel

An untrapped error occurred.
(Traceback was logged 24-12-26 21:15:13).
```

**Comment by soma-satoro** [comment]
Resolved; +help jobs now works properly, and the default buckets are listed. Jobs also informs the user when the job is placed (as well as staff on a specific [Jobs] channel. +help jobs should also be more sensible and easier to parse (read: friendly to everyone _as well as_ Marid)
