### ISSUE TITLE
Say in OOC area causes TB

### ISSUE THREAD

**Issue by biscuitWizard** [Dies-Irae-mu/game#45]
repro:
type unpuppet
type say test

get:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py",
line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "/root/game/commands/CmdSay.py", line 44, in func
    self.send_pose_break()
  File "/root/game/commands/CmdPose.py", line 14, in send_pose_break
    obj for obj in caller.location.contents
                   ^^^^^^^^^^^^^^^
AttributeError: 'Account' object has no attribute 'location'
```

**Comment by soma-satoro** [comment]
Given that you need to have a location (defaultRoom) to utilize the say/pose/emit commands on the game, this is expected behavior. Additionally, we have multiple ways to speak OOCly to one another from channels to an in-room ooc command to a Discord server. As such, we're not going to address this at this time.
