### ISSUE TITLE
Command parsing in +shortdesc

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#48]
Repro steps
1. Be a regular player
2.  `+shortdesc me=Some funny text`

Expected Behavior
Any one of the following: 
1. Set my shortdesc to 'me=Some funny text'
2. An error message saying that only builders can use shortdesc this way
3. Recognize that 'me' is me, and set my shortdesc to 'Some funny text'

Actual behavior:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py", line 625, in _run_command
    yield cmd.parse()
          ^^^^^^^^^^^
  File "/root/game/commands/CmdShortDesc.py", line 25, in parse
    self.target_name, self.shortdesc = [part.strip() for part in args.split("=", 1)].strip()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'strip'

An untrapped error occurred.
(Traceback was logged 24-12-27 07:07:36).
```

**Comment by soma-satoro** [comment]
Although both the helpfile and command suggestion when looking at a room states to use +shortdesc <desc>, I changed it to allow the use of +shortdesc me=<desc>. Resolved.
