### ISSUE TITLE
Issues with making notes private

### ISSUE THREAD

**Issue by Kittenapped** [Dies-Irae-mu/game#56]
When I type either:
+note/status 3=private
+note/status initials=private

I get this:
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "/root/game/commands/CmdNotes.py", line 74, in func
    self.change_note_status()
  File "/root/game/commands/CmdNotes.py", line 325, in change_note_status
    self.caller.change_note_status(note_name, is_public)
  File "/root/game/typeclasses/characters.py", line 488, in change_note_status
    if self.character_sheet:
       ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
evennia.objects.models.ObjectDB.character_sheet.RelatedObjectDoesNotExist: Character has no character_sheet.. Did you mean: 'db_character_sheet'?

An untrapped error occurred.
(Traceback was logged 24-12-29 15:22:24).
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "/root/game/commands/CmdNotes.py", line 74, in func
    self.change_note_status()
  File "/root/game/commands/CmdNotes.py", line 325, in change_note_status
    self.caller.change_note_status(note_name, is_public)
  File "/root/game/typeclasses/characters.py", line 488, in change_note_status
    if self.character_sheet:
       ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
evennia.objects.models.ObjectDB.character_sheet.RelatedObjectDoesNotExist: Character has no character_sheet.. Did you mean: 'db_character_sheet'?

An untrapped error occurred.
(Traceback was logged 24-12-29 15:22:50).

**Comment by Kittenapped** [comment]
I was attempting to set notes to the different categories on the notes and everything went into general.

![Screenshot (232)](https://github.com/user-attachments/assets/25deea92-e23e-478e-a7ff-811d0fff0537)

**Comment by soma-satoro** [comment]
This has been resolved. Notes can be made private with either +note/private # or +note/status #=private (and vice-versa for 'public').
