### ISSUE TITLE
+peek no worky?

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#66]
Repro Steps:
1. `+peek` (and fail)

Expected Outcome:
```
Gnosis Roll: 0 successes against difficulty 8.
You're blind, bruh.
```

Actual Outcome:
```
Gnosis Roll: 0 successes against difficulty 8
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "/root/game/commands/CmdUmbraInteraction.py", line 30, in func
    self.do_peek()
  File "/root/game/commands/CmdUmbraInteraction.py", line 79, in do_peek
    result = self.caller.location.peek_umbra(self.caller)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/game/typeclasses/rooms.py", line 279, in peek_umbra
    formatted_desc = self.format_description(self.db.umbra_desc)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/game/typeclasses/rooms.py", line 292, in format_description
    paragraphs = desc.split('
', '
')
                 ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer

An untrapped error occurred.
(Traceback was logged 24-12-30 21:36:14).
```

**Comment by Darcness** [comment]
Heh.  yeah, makes sense.  `string.split()` in python takes a string and an integer (max parts).  Maybe that should be `.replace()`?

**Comment by soma-satoro** [comment]
Yep, replace did the trick. Will be pushed in next commit.
